name: CI/CD Pipeline

on:
  push:
    branches:
      - homol
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t mysql-webapp-api:latest -f ./app/Dockerfile ./app

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.HOME_LAB_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 192.168.0.10 >> ~/.ssh/known_hosts
      env:
        HOME_LAB_SSH_KEY: ${{ secrets.HOME_LAB_SSH_KEY }}

    - name: Deploy to Home Lab
      run: |
        echo "Deploying to home lab"
        ssh -o StrictHostKeyChecking=no root@192.168.0.10 << 'EOF'
          docker stop mysql-webapp-api || true
          docker rm mysql-webapp-api || true
          docker run -d -p 8001:8000 --name mysql-webapp-api mysql-webapp-api:latest
        EOF
      env:
        HOME_LAB_SSH_KEY: ${{ secrets.HOME_LAB_SSH_KEY }}
