name: CI/CD Pipeline

on:
  push:
    branches:
      - homol

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/mysql-webapp-api:latest ./app/Dockerfile

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}/mysql-webapp-api

    - name: Deploy to Home Lab
      env:
        SSH_PRIVATE_KEY: ${{ secrets.HOME_LAB_SSH_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        ssh -o StrictHostKeyChecking=no root@192.168.0.10 << 'EOF'
          docker pull ghcr.io/${{ github.repository }}/mysql-webapp-api:latest
          docker stop mysql-webapp-api || true
          docker rm mysql-webapp-api || true
          docker run -d -p 8000:8000 --name myapp ghcr.io/${{ github.repository }}/mysql-webapp-api:latest
        EOF

      
